autoload:
  vundle: https://raw.github.com/gmarik/vundle/master/autoload/vundle.vim

autoload/vundle:
  config: https://raw.github.com/gmarik/vundle/master/autoload/vundle/config.vim
  installer: https://raw.github.com/gmarik/vundle/master/autoload/vundle/installer.vim
  scripts: https://raw.github.com/gmarik/vundle/master/autoload/vundle/scripts.vim

doc:
  vundle: https://raw.github.com/gmarik/vundle/master/doc/vundle.txt
